### PR TITLE
release v0.3.6

### PR DESCRIPTION
**Pull request by Emilgardis**

### CODE REVIEW

**Comment by Emilgardis** [comment]
interestingly, the tag did not trigger ci

https://github.com/rust-embedded/cargo-binutils/actions/workflows/release.yml

**Comment by Emilgardis** [comment]
@burrbull could you explain how releases are done now with the new CI, I'm not sure I understand it.

Do i make a tag vx.y.z and push it? or do I make a GH release with that tag?

**Review by burrbull — APPROVED** [review]

**Comment by burrbull** [comment]
> Do i make a tag vx.y.z and push it? or do I make a GH release with that tag?

First

**Comment by Emilgardis** [comment]
Need to change the date in changelog

Ill edit the pr when im home in 4-5 hours.

**Pull request merged**
