### PR TITLE
Clean up error handling and metadata parsing

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by therealprof** [comment]
@adamgreig The promised cleanup...

**Comment by adamgreig** [comment]
bors try

**Comment by therealprof** [comment]
bors retry

**Comment by therealprof** [comment]
Hm, weird. No idea what the problem might be and/or how to work around this. Maybe need to do without cleanup then?

**Comment by therealprof** [comment]
@adamgreig It seems that Windows is rather particular about how its pipes are drained...

**Comment by therealprof** [comment]
I've put in another simplification and replaced an unwrap by an expect. I hope Windows will still be happy but after the next CI run this should finally be ready to go.

I've also started preparing the release.

**Pull request merged**
