### PR TITLE
add cargo `--config` arg

### PR DESCRIPTION
**Pull request by PhilippMolitor**
self-explanatory, requested in #143

### CODE REVIEW

**Review by Emilgardis — APPROVED** [review]

**Comment by burrbull** [comment]
@PhilippMolitor could you rebase your PRs on current master channel?

**Comment by PhilippMolitor** [comment]
will do as soon as i am home!

**Comment by Emilgardis** [comment]
please remove the merge commit, use a rebase instead

**Comment by PhilippMolitor** [comment]
does this look right?

**Review by burrbull — APPROVED** [review]

**Pull request merged**
