### PR TITLE
v0.1.7

### PR DESCRIPTION
**Pull request by berkus**
- Fixed detection of workspaces (globs and relative paths)

### CODE REVIEW

**Comment by berkus** [comment]
bors r=therealprof

**Comment by berkus** [comment]
@therealprof here

**Comment by berkus** [comment]
Ok, hang on.

**Comment by therealprof** [comment]
Oh, and sorry for noticing this just now but would you mind updating the metadata in Cargo.toml to put to the new location of the repo instead of the old location?

**Comment by berkus** [comment]
@therealprof updated.

Two missing commits folded into single changelog line, as they touch the same rust-* tools.

**Comment by berkus** [comment]
Ah, sec, Cargo location update coming up

**Comment by berkus** [comment]
@therealprof Ok, now all done.

**Comment by berkus** [comment]
You're welcome!

**Comment by berkus** [comment]
Will the merge trigger actual release build and crate publish?

**Comment by therealprof** [comment]
Nope, I need to do that manually once the PR is merge.

**Comment by berkus** [comment]
I see. Hope this all works and I'll be able to test out the new cargo-binutils this evening.

**Comment by therealprof** [comment]
No worries, once the PR is in, I'll immediately publish.

**Comment by therealprof** [comment]
https://crates.io/crates/cargo-binutils

**Comment by berkus** [comment]
👍  gonna test it out.

**Pull request merged**
