### PR TITLE
Don't print compiler messages when --quiet is passed

### PR DESCRIPTION
**Pull request by toothbrush7777777**

### CODE REVIEW

**Comment by toothbrush7777777** [comment]
The CI error has nothing to do with this pull request. It appears that LLVM have renamed `-arch-name` to `--arch-name`.

**Comment by therealprof** [comment]
> The CI error has nothing to do with this pull request. It appears that `-arch-name` has been renamed to `--arch-name` in LLVM 11.

Meh. :(

**Comment by therealprof** [comment]
Seems like double hyphen style long options also work before LLVM 11 and they've deprecated the single hyphen ones in LLVM 11.

I've created #92 to change that, let's see whether CI agrees...

**Review by therealprof — APPROVED** [review]
LGTM, thanks!

bors r+

**Pull request merged**
